"groups":
- "name": "django"
  "rules":
  - "alert": "DjangoMigrationsUnapplied"
    "annotations":
      "description": "The job {{ $labels.job }} has unapplied migrations."
      "summary": "Django unapplied migrations."
    "expr": |
      sum(
        increase(
          django_migrations_unapplied_total{
            django
          }[15m]
        )
      ) by (namespace, job)
      > 1
    "labels":
      "severity": "warning"
  - "alert": "DjangoHighHttp4xxErrorRate"
    "annotations":
      "dashboard_url": "django-requests-by-view-jkwq?var-job={{ $labels.job }}&var-view={{ $labels.view }}"
      "description": "More than 5% HTTP requests with status 4xx for {{ $labels.job }}/{{ $labels.view }} the past 5m."
      "summary": "Django high HTTP 4xx error rate."
    "expr": |
      sum(
        rate(
          django_http_responses_total_by_status_view_method_created{
            django,
            status=~"^4.*",
            view!~"health_check:health_check_home|prometheus-django-metrics"
          }[5m]
        )
      )  by (namespace, job, view)
      /
      sum(
        rate(
          django_http_responses_total_by_status_view_method_created{
            django,
            view!~"health_check:health_check_home|prometheus-django-metrics"
          }[5m]
        )
      )  by (namespace, job, view)
      * 100 > 5
    "for": "30s"
    "labels":
      "severity": "warning"
  - "alert": "DjangoHighHttp5xxErrorRate"
    "annotations":
      "dashboard_url": "django-requests-by-view-jkwq?var-job={{ $labels.job }}&var-view={{ $labels.view }}"
      "description": "More than 5% HTTP requests with status 5xx for {{ $labels.job }}/{{ $labels.view }} the past 5m."
      "summary": "Django high HTTP 5xx error rate."
    "expr": |
      sum(
        rate(
          django_http_responses_total_by_status_view_method_created{
            django,
            status=~"^5.*",
            view!~"health_check:health_check_home|prometheus-django-metrics"
          }[5m]
        )
      )  by (namespace, job, view)
      /
      sum(
        rate(
          django_http_responses_total_by_status_view_method_created{
            django,
            view!~"health_check:health_check_home|prometheus-django-metrics"
          }[5m]
        )
      )  by (namespace, job, view)
      * 100 > 5
    "for": "30s"
    "labels":
      "severity": "warning"
